### PR TITLE
fix: finished conflict container-2 #8

### PR DESCRIPTION
**Pull request by southAndy**
fix conflict

### CODE REVIEW

**Review by behappywendy — DISMISSED** [review]

**Review by southAndy — COMMENTED** [review]
gogo!!

**Review by behappywendy — APPROVED** [review]

**Review by cc5324 — APPROVED** [review]
approved

**Comment by southAndy** [comment]
* fix: finished conflict container-2 #8
* fix: remove wrong package-lock.json #8

**Comment by southAndy** [comment]
* fix: finished conflict container-2 #8
* fix: remove wrong package-lock.json #8

**Pull request merged**
